import { DISCORD_LINK, GITHUB_LINK } from "@/constants";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "../ui/accordion";

export default function FAQ() {
  return (
    <Accordion type="multiple">
      <AccordionItem value="pricing">
        <AccordionTrigger>How much does Repbot cost?</AccordionTrigger>
        <AccordionContent>
          <p className="mb-3">
            Our goal is for Repbot to be completely free to use with no paid
            add-ons or usage tiers. However, giving away stuff for free does not
            make for financial sustainability, and we want to make sure you can
            rely on Repbot to help you run your business for a long time.
          </p>
          <p className="mb-3">
            To that end, our plan for monetization (at the moment) is to sell
            anonymized, aggregate reports on the sponsorship industry to brands
            and other talent agencies based on the data that Repbot collects
            about the deals that come through the service.
          </p>
          <p className="mb-3">
            So, yes, this is another free product that plans on selling your
            data to advertisers 😮‍💨.
          </p>
          <p>
            ☝️ However, expand the next question to see how <i>you</i> can
            actually share in the profits that come from the sale of your data.
          </p>
        </AccordionContent>
      </AccordionItem>
      <AccordionItem value="coop">
        <AccordionTrigger>
          <span>
            What's with the <code className="inline-block">`.coop`</code>?
          </span>
        </AccordionTrigger>
        <AccordionContent>
          <p className="mb-3">
            With Repbot, we are pioneering a new-old way of doing business: the
            cooperative. A coop is a business that is owned and run by its
            customers and employees.
          </p>

          <p className="mb-3">
            In a cooperative, there aren't VCs or shareholders. There are only{" "}
            <i>member-owners</i>: people who contribute to the cooperative in
            order to benefit from its services. These <i>member-owners</i> all
            have equal voting rights to help set the direction of the
            cooperative and all (usually) receive an equitable proportion of
            profits generated by the cooperative based on how much they've
            contributed to its revenue.
          </p>

          <p className="mb-3">
            Repbot is (soon to be) a registered cooperative. That means that you
            can (soon) pay a membership fee (probably ~$50/year) and become a{" "}
            <i>member-owner</i> of Repbot. This will entitle you to a variety of
            benefits including a bi-annual membership dividend of profits
            generated from the sale of Repbot's data (in proportion to some
            criteria that is TBD).
          </p>

          <p className="mb-3">
            The details of exactly <i>how</i> this cooperative structure is
            going to work is still under active development. This is a way of
            doing business on the internet that we{" "}
            <a
              href="https://start.coop"
              target="_blank"
              className="underline opacity-80"
            >
              and a few other companies
            </a>{" "}
            are pioneering. So, we appreciate your patience as we try to model a
            more equitable and just online economy.
          </p>

          <p>
            And if you're excited by this concept and want to help us fill in
            the blanks,{" "}
            <a
              href={DISCORD_LINK}
              target="_blank"
              className="underline opacity-80"
            >
              join our Discord server
            </a>
            .
          </p>
        </AccordionContent>
      </AccordionItem>
      <AccordionItem value="contracting">
        <AccordionTrigger>
          Does Repbot handle contracts/invoicing/payment?
        </AccordionTrigger>
        <AccordionContent>
          <p className="mb-3">
            We do not currently plan on ever handling these aspects of your deal
            flow.
          </p>

          <p className="mb-3">
            We understand that there are serious problems with contracting when
            self-managing - like predatory licensing terms - but we feel these
            are problems best solved with educational material rather than
            process automation.
          </p>

          <p className="mb-3">
            In terms of invoicing and payment, we believe that there are more
            specialized, secure, and cheaper alternatives creators have access
            to that can provide a better experience than we have the resources
            to build at this time.
          </p>
          <p>
            ☝️ However, as mentioned above, Repbot's cooperative structure means
            that if you, the <i>member-owners</i> of Repbot, vote to dedicate
            time to this or any other problem, that's what the organization will
            focus on. This is <i>your</i> company.
          </p>
        </AccordionContent>
      </AccordionItem>
      <AccordionItem value="opensource">
        <AccordionTrigger>Is Repbot open source?</AccordionTrigger>
        <AccordionContent>
          <p className="mb-3">
            Yes! The code for Repbot is completely open source and available{" "}
            <a href={GITHUB_LINK} className="underline hover:opacity-80">
              on Github
            </a>
            .
          </p>

          <p>
            If you're interested in contributing to Repbot's codebase, please
            reach out to us{" "}
            <a href={DISCORD_LINK} className="underline hover:opacity-80">
              on Discord
            </a>
            .
          </p>
        </AccordionContent>
      </AccordionItem>
    </Accordion>
  );
}
